import os
from pathlib import Path

import streamlit as st
import plotly.graph_objects as go

from src.agents import SKILL_NAMES, EMOTION_NAMES
from gui.dashboard.state import generate_portrait_prompt


def render_events_tab():
    st.caption("World events generated by the LLM narrator — plagues, discoveries, disasters. Each event has a health impact and may boost a skill. GRN = positive, YEL = mild negative, RED = severe. All events accumulate until you create a new sim.")
    events = st.session_state.events_log
    if events:
        st.markdown(f"**{len(events)} total events**")
        for e in reversed(events):
            hdelta = e["effects"].get("health_delta", 0)
            icon = "RED" if hdelta < -0.05 else "YEL" if hdelta < 0 else "GRN"
            skill = e["effects"].get("skill_boost") or "--"
            with st.container():
                st.markdown(f"**[{icon}] t={e['tick']}** -- `{e['name']}`")
                st.caption(f"{e['description']}")
                st.caption(f"Target: {e['effects'].get('target')} | Health: {hdelta:+.2f} | Skill boost: {skill}")
                st.divider()
    else:
        st.info("No events yet.")


def render_narratives_tab():
    st.caption("Prose narratives about the state of civilization. Generated every 100 ticks (configurable). Uses LLM when available, otherwise generates from simulation data.")
    narratives = st.session_state.narratives_log
    if narratives:
        for n in reversed(narratives):
            st.markdown(f"### Tick {n['tick']}")
            st.markdown(n["text"])
            st.divider()
    else:
        st.info("No narratives yet. Run more ticks — narratives generate every 100 ticks.")


def render_protagonists_tab(engine, alive, sidebar_state=None):
    st.caption("Up to 5 tracked agents whose stories you follow closely. Auto-selected by generation + bonds + intelligence, or manually chosen. Inner monologue and portrait prompts generated automatically.")
    st.markdown("#### Protagonist Agents")

    # Show all protagonists — alive AND dead (their stories persist)
    prot_agents = [a for a in engine.agents if a.is_protagonist]
    # Sort: alive first, then by id
    prot_agents.sort(key=lambda a: (not a.alive, a.id))

    if prot_agents:
        for agent in prot_agents:
            name = agent.protagonist_name or f"Agent #{agent.id}"

            # ── Status tags ──
            tags = []
            if not agent.alive:
                tags.append(("\u2620\ufe0f", "DECEASED"))
            if agent.is_anomaly:
                tags.append(("\U0001f7e1", "THE ONE"))
            if agent.redpilled:
                tags.append(("\U0001f534", "REDPILLED"))
            if agent.is_exile:
                tags.append(("\U0001f7e3", "EXILE"))
            if agent.is_sentinel:
                tags.append(("\u26ab", "SENTINEL"))
            if agent.awareness > 0.5:
                tags.append(("\U0001f441\ufe0f", f"AWARE {agent.awareness:.0%}"))
            if agent.faction_id is not None:
                faction = next((f for f in engine.factions if f.id == agent.faction_id), None)
                if faction:
                    tags.append(("\u2694\ufe0f", faction.name))
            if agent.trauma > 0.3:
                tags.append(("\U0001fa78", f"TRAUMA {agent.trauma:.0%}"))

            tag_html = " ".join(
                f'<span style="background:rgba(255,215,0,0.1);border:1px solid #5a8a5a;'
                f'border-radius:8px;padding:2px 8px;font-size:0.7em;color:#ffd700;">'
                f'{icon} {label}</span>'
                for icon, label in tags
            )

            # ── Visual character card ──
            dom_emo = agent.dominant_emotion or "neutral"
            emo_icons = {"happiness": "\U0001f60a", "fear": "\U0001f628", "anger": "\U0001f621",
                         "grief": "\U0001f622", "hope": "\u2728", "neutral": "\U0001f610"}
            phase_icons = {"infant": "\U0001f476", "child": "\U0001f9d2", "adolescent": "\U0001f9d1",
                           "adult": "\U0001f9d1\u200d\U0001f4bc" if agent.sex == "M" else "\U0001f469\u200d\U0001f4bc",
                           "elder": "\U0001f9d3"}

            # Health bar
            hp_pct = int(agent.health * 100)
            hp_color = "#00ff88" if hp_pct > 60 else "#ffaa00" if hp_pct > 30 else "#ff4466"
            phase_icon = phase_icons.get(agent.phase, "\U0001f9d1")
            emo_icon = emo_icons.get(dom_emo, "\U0001f610")

            # Check for AI portrait
            run_id = st.session_state.get("run_id", "unknown")
            portrait_dir = Path("output/portraits") / str(run_id)
            agent_portraits = sorted(
                portrait_dir.glob(f"agent_{agent.id}_t*.png"),
                key=lambda p: p.stat().st_mtime, reverse=True,
            ) if portrait_dir.exists() else []
            has_portrait = len(agent_portraits) > 0

            # Card layout: portrait thumbnail + info
            card_portrait_col, card_info_col = st.columns([1, 3] if has_portrait else [0.001, 4])

            with card_portrait_col:
                if has_portrait:
                    st.image(str(agent_portraits[0]), width='stretch')

            with card_info_col:
                st.markdown(f"""
                <div style="background:linear-gradient(135deg, #0a1f0a, #040f04);border:1px solid #00ff88;
                            border-radius:12px;padding:16px;margin:8px 0;font-family:'JetBrains Mono',monospace;">
                    <div style="display:flex;justify-content:space-between;align-items:center;">
                        <div>
                            <span style="font-size:2em;">{phase_icon}</span>
                            <span style="font-size:1.4em;font-weight:700;color:#ffd700;margin-left:8px;
                                         font-family:'Space Grotesk',sans-serif;">{name}</span>
                            <span style="color:#5a8a5a;font-size:0.8em;"> #{agent.id}</span>
                        </div>
                        <div style="font-size:1.5em;">{emo_icon}</div>
                    </div>
                    <div style="margin-top:6px;">{tag_html}</div>
                    <div style="display:flex;gap:20px;margin-top:12px;color:#b0d0b0;font-size:0.8em;">
                        <div>Age <span style="color:#00ff88;font-weight:700;">{agent.age}</span></div>
                        <div>{agent.phase.upper()}</div>
                        <div>Gen <span style="color:#00ff88;">{agent.generation}</span></div>
                        <div>IQ <span style="color:#00ff88;">{agent.intelligence:.3f}</span></div>
                        <div>Bonds <span style="color:#00ccff;">{len(agent.bonds)}</span></div>
                        <div>Wealth <span style="color:#ffaa00;">{agent.wealth:.1f}</span></div>
                    </div>
                    <div style="margin-top:8px;">
                        <div style="font-size:0.7em;color:#5a8a5a;margin-bottom:2px;">HP {hp_pct}%</div>
                        <div style="background:#0a0a0a;border-radius:4px;height:8px;width:100%;">
                            <div style="background:{hp_color};border-radius:4px;height:8px;width:{hp_pct}%;
                                        transition:width 0.3s;"></div>
                        </div>
                    </div>
                </div>
                """, unsafe_allow_html=True)

            # Enlarge portrait dialog
            if has_portrait:
                @st.dialog(f"Portrait — {name}")
                def _show_portrait(img_path, agent_name, portraits_list):
                    st.image(str(img_path), caption=agent_name, width='stretch')
                    if len(portraits_list) > 1:
                        st.markdown("#### Previous Portraits")
                        for p in portraits_list[1:5]:
                            tick_str = p.stem.split("_t")[-1]
                            st.image(str(p), caption=f"t={tick_str}", width='stretch')

                if st.button(f"View Portrait Full Size", key=f"enlarge_portrait_{agent.id}"):
                    _show_portrait(agent_portraits[0], name, agent_portraits)

            # Skills radar + emotions side by side
            card_left, card_right = st.columns([1, 1])

            with card_left:
                fig_prot_sk = go.Figure()
                sk_vals = [agent.skills.get(s, 0) for s in SKILL_NAMES]
                fig_prot_sk.add_trace(go.Scatterpolar(
                    r=sk_vals + [sk_vals[0]],
                    theta=SKILL_NAMES + [SKILL_NAMES[0]],
                    fill="toself", fillcolor="rgba(255,215,0,0.1)",
                    line=dict(color="#ffd700", width=2),
                ))
                fig_prot_sk.update_layout(
                    template="plotly_dark", paper_bgcolor="#030d03", plot_bgcolor="#040f04",
                    height=220, margin=dict(t=10, b=10, l=30, r=30),
                    polar=dict(bgcolor="#040f04",
                               radialaxis=dict(visible=True, range=[0, 1], gridcolor="#0a2a0a", showticklabels=False),
                               angularaxis=dict(gridcolor="#0a2a0a")),
                    font=dict(family="JetBrains Mono", color="#5a8a5a", size=9),
                    showlegend=False,
                )
                st.plotly_chart(fig_prot_sk, width='stretch', key=f"prot_radar_{agent.id}")

            with card_right:
                # Emotion bars
                st.markdown("**Emotional State**")
                for emo_name in EMOTION_NAMES:
                    val = agent.emotions.get(emo_name, 0)
                    bar_colors = {"happiness": "#00ff88", "fear": "#aa66ff", "anger": "#ff4466",
                                  "grief": "#00ccff", "hope": "#ffd700"}
                    bar_col = bar_colors.get(emo_name, "#5a8a5a")
                    st.markdown(
                        f'<div style="display:flex;align-items:center;gap:8px;font-size:0.75em;margin:2px 0;">'
                        f'<span style="width:70px;color:#5a8a5a;">{emo_name}</span>'
                        f'<div style="flex:1;background:#0a0a0a;border-radius:3px;height:6px;">'
                        f'<div style="background:{bar_col};border-radius:3px;height:6px;width:{int(val*100)}%;"></div>'
                        f'</div>'
                        f'<span style="color:{bar_col};width:30px;text-align:right;">{val:.0%}</span>'
                        f'</div>', unsafe_allow_html=True
                    )

                # Trait summary
                st.markdown("")
                st.markdown("**Key Traits**")
                trait_items = [
                    ("Resilience", agent.traits.resilience, "#00ff88"),
                    ("Curiosity", agent.traits.curiosity, "#00ccff"),
                    ("Charisma", agent.traits.charisma, "#ffd700"),
                    ("Aggression", agent.traits.aggression, "#ff4466"),
                ]
                for t_name, t_val, t_col in trait_items:
                    st.markdown(
                        f'<div style="display:flex;align-items:center;gap:8px;font-size:0.75em;margin:2px 0;">'
                        f'<span style="width:80px;color:#5a8a5a;text-align:right;">{t_name}</span>'
                        f'<div style="flex:1;background:#0a0a0a;border-radius:3px;height:6px;">'
                        f'<div style="background:{t_col};border-radius:3px;height:6px;width:{int(t_val*100)}%;"></div>'
                        f'</div>'
                        f'<span style="color:{t_col};width:30px;text-align:right;">{t_val:.0%}</span>'
                        f'</div>', unsafe_allow_html=True
                    )

            # Portrait generation
            with st.expander("\U0001f3a8 Generate / Update Portrait"):
                if st.button(f"Generate New Portrait", key=f"gen_portrait_{agent.id}",
                             width='stretch'):
                    s = sidebar_state or {}
                    with st.spinner("Generating portrait..."):
                        from src.portrait import PortraitGenerator
                        from dashboard.runner import build_narrator

                        cfg = st.session_state.get("cfg")
                        narrator = build_narrator(cfg, s) if cfg else None

                        gen = PortraitGenerator(
                            hf_token=s.get("portrait_hf_token") or os.environ.get("HF_TOKEN"),
                            hf_model=s.get("portrait_hf_model", "black-forest-labs/FLUX.1-schnell"),
                            diffuser_model=s.get("portrait_diffuser_model", "flux.1-schnell"),
                        )
                        tick = engine.state.current_tick
                        result_path = gen.generate_portrait(agent, narrator, run_id, tick)

                    if result_path and Path(result_path).exists():
                        st.image(result_path, caption=f"Portrait of {name} (t={tick})", width='stretch')
                        st.success(f"Portrait saved via {gen.provider_name}")
                        st.rerun()
                    else:
                        st.error("Portrait generation failed. Check that HF token is set or OllamaDiffuser is running.")

                with st.expander("View image prompt"):
                    portrait_prompt = generate_portrait_prompt(agent)
                    st.code(portrait_prompt, language=None)

            # ── Relationships (visual) ──
            if agent.bonds:
                with st.expander(f"\U0001f91d Relationships ({len(agent.bonds)})", expanded=True):
                    agent_map = {a.id: a for a in engine.agents}

                    # Group by type
                    bond_groups = {}
                    for b in agent.bonds:
                        bond_groups.setdefault(b.bond_type, []).append(b)

                    type_config = {
                        "mate": ("\u2764\ufe0f", "Partner", "#ff4466"),
                        "friend": ("\U0001f91d", "Friends", "#00ccff"),
                        "family": ("\U0001f9ec", "Family", "#00ff88"),
                        "rival": ("\u2694\ufe0f", "Rivals", "#ff8844"),
                        "child": ("\U0001f476", "Children", "#aa66ff"),
                        "parent": ("\U0001f9ec", "Parents", "#00ff88"),
                        "mentor": ("\U0001f393", "Mentors", "#ffd700"),
                    }

                    for btype, bonds in bond_groups.items():
                        icon, label, color = type_config.get(btype, ("\U0001f517", btype.title(), "#5a8a5a"))
                        st.markdown(f"**{icon} {label}**")
                        for b in sorted(bonds, key=lambda x: -x.strength):
                            target = agent_map.get(b.target_id)
                            if target:
                                t_name = target.protagonist_name or f"#{target.id}"
                                status = "" if target.alive else " \u2620\ufe0f"
                                # Strength bar
                                bar_w = int(b.strength * 100)
                                st.markdown(
                                    f'<div style="display:flex;align-items:center;gap:8px;font-size:0.8em;margin:3px 0;">'
                                    f'<span style="min-width:100px;color:{color};">{t_name}{status}</span>'
                                    f'<div style="flex:1;background:#0a0a0a;border-radius:3px;height:6px;max-width:150px;">'
                                    f'<div style="background:{color};border-radius:3px;height:6px;width:{bar_w}%;"></div>'
                                    f'</div>'
                                    f'<span style="color:#5a8a5a;font-size:0.85em;">{b.strength:.0%}</span>'
                                    f'<span style="color:#3a5a3a;font-size:0.75em;">t={b.formed_at}</span>'
                                    f'</div>', unsafe_allow_html=True
                                )
                            else:
                                st.markdown(f'<span style="color:#5a8a5a;font-size:0.8em;">#{b.target_id} (unknown)</span>', unsafe_allow_html=True)

                    # Bond network mini-graph
                    if len(agent.bonds) >= 2:
                        fig_bonds = go.Figure()
                        # Ego node
                        fig_bonds.add_trace(go.Scatter(
                            x=[0.5], y=[0.5], mode="markers+text",
                            marker=dict(size=20, color="#ffd700", symbol="star"),
                            text=[name[:10]], textposition="top center",
                            textfont=dict(size=10, color="#ffd700"),
                            showlegend=False,
                        ))
                        # Bond nodes in a circle
                        import math
                        bond_colors = {"mate": "#ff4466", "friend": "#00ccff", "family": "#00ff88",
                                       "rival": "#ff8844", "child": "#aa66ff", "parent": "#00ff88"}
                        n = len(agent.bonds)
                        for i, b in enumerate(agent.bonds):
                            angle = 2 * math.pi * i / n
                            bx = 0.5 + 0.35 * math.cos(angle)
                            by = 0.5 + 0.35 * math.sin(angle)
                            bc = bond_colors.get(b.bond_type, "#5a8a5a")
                            target = agent_map.get(b.target_id)
                            t_label = (target.protagonist_name or f"#{b.target_id}")[:8] if target else f"#{b.target_id}"
                            # Edge
                            fig_bonds.add_trace(go.Scatter(
                                x=[0.5, bx], y=[0.5, by], mode="lines",
                                line=dict(color=bc, width=b.strength * 4),
                                opacity=0.6, showlegend=False,
                            ))
                            # Node
                            alive_marker = "circle" if (target and target.alive) else "x"
                            fig_bonds.add_trace(go.Scatter(
                                x=[bx], y=[by], mode="markers+text",
                                marker=dict(size=12, color=bc, symbol=alive_marker),
                                text=[t_label], textposition="bottom center",
                                textfont=dict(size=8, color=bc),
                                showlegend=False,
                            ))
                        fig_bonds.update_layout(
                            template="plotly_dark", paper_bgcolor="#030d03", plot_bgcolor="#040f04",
                            height=250, margin=dict(t=5, b=5, l=5, r=5),
                            xaxis=dict(range=[0, 1], showticklabels=False, showgrid=False),
                            yaxis=dict(range=[0, 1], showticklabels=False, showgrid=False, scaleanchor="x"),
                        )
                        st.plotly_chart(fig_bonds, width='stretch', key=f"prot_bonds_{agent.id}")

            # ── Life Stats ──
            with st.expander("\U0001f4ca Life Stats", expanded=False):
                stat_cols = st.columns(3)

                # Belief compass
                with stat_cols[0]:
                    st.markdown("**Beliefs**")
                    fig_bel = go.Figure()
                    bel_axes = list(agent.beliefs.keys())
                    bel_vals = [agent.beliefs[a] for a in bel_axes]
                    bel_labels = {
                        "individualism": "Individual",
                        "tradition": "Tradition",
                        "system_trust": "Sys Trust",
                        "spirituality": "Spiritual",
                    }
                    fig_bel.add_trace(go.Scatterpolar(
                        r=[abs(v) for v in bel_vals] + [abs(bel_vals[0])],
                        theta=[bel_labels.get(a, a) for a in bel_axes] + [bel_labels.get(bel_axes[0], bel_axes[0])],
                        fill="toself", fillcolor="rgba(0,204,255,0.1)",
                        line=dict(color="#00ccff", width=2),
                    ))
                    fig_bel.update_layout(
                        template="plotly_dark", paper_bgcolor="#030d03", plot_bgcolor="#040f04",
                        height=180, margin=dict(t=5, b=5, l=25, r=25),
                        polar=dict(bgcolor="#040f04",
                                   radialaxis=dict(visible=True, range=[0, 1], gridcolor="#0a2a0a", showticklabels=False),
                                   angularaxis=dict(gridcolor="#0a2a0a")),
                        font=dict(family="JetBrains Mono", color="#5a8a5a", size=8),
                        showlegend=False,
                    )
                    st.plotly_chart(fig_bel, width='stretch', key=f"prot_beliefs_{agent.id}")

                # Key numbers
                with stat_cols[1]:
                    st.markdown("**Identity**")
                    st.markdown(
                        f'<div style="font-family:JetBrains Mono,monospace;font-size:0.78em;line-height:2;">'
                        f'<div>Awareness <span style="color:{"#ff4466" if agent.awareness > 0.5 else "#5a8a5a"};">{agent.awareness:.0%}</span></div>'
                        f'<div>Extremism <span style="color:{"#ff8844" if agent.belief_extremism > 0.5 else "#5a8a5a"};">{agent.belief_extremism:.0%}</span></div>'
                        f'<div>Trauma <span style="color:{"#ff4466" if agent.trauma > 0.3 else "#5a8a5a"};">{agent.trauma:.0%}</span></div>'
                        f'<div>Wealth <span style="color:#ffaa00;">{agent.wealth:.1f}</span></div>'
                        f'<div>Dynasty <span style="color:#00ff88;">{len(agent.child_ids)} children</span></div>'
                        f'</div>', unsafe_allow_html=True
                    )

                # Faction
                with stat_cols[2]:
                    st.markdown("**Faction**")
                    if agent.faction_id is not None:
                        faction = next((f for f in engine.factions if f.id == agent.faction_id), None)
                        if faction:
                            is_leader = faction.leader_id == agent.id
                            st.markdown(
                                f'<div style="font-family:JetBrains Mono,monospace;font-size:0.78em;line-height:2;">'
                                f'<div style="color:#ffd700;font-weight:700;">{faction.name}</div>'
                                f'<div>{"LEADER" if is_leader else "Member"}</div>'
                                f'<div>Members: {sum(1 for a in engine.agents if a.faction_id == faction.id and a.alive)}</div>'
                                f'</div>', unsafe_allow_html=True
                            )
                        else:
                            st.caption("Faction dissolved")
                    else:
                        st.caption("Unaffiliated — lone wolf")

                # Memory timeline
                if agent.memory and len(agent.memory) > 3:
                    st.markdown("**Life Timeline**")
                    key_events = [m for m in agent.memory if any(k in m.get("event", "").lower()
                                  for k in ["born", "died", "breakthrough", "bond", "mate", "whisper",
                                            "red pill", "divine", "prophet", "war", "healed", "smote"])]
                    if not key_events:
                        key_events = agent.memory[-10:]  # fallback to recent
                    timeline_html = '<div style="border-left:2px solid #0a2a0a;padding-left:12px;margin:8px 0;">'
                    for m in key_events[-12:]:
                        tick_val = m.get("tick", 0)
                        event_text = m.get("event", "...")
                        # Color by event type
                        if "died" in event_text.lower() or "death" in event_text.lower():
                            dot_color = "#ff4466"
                        elif "born" in event_text.lower() or "mate" in event_text.lower():
                            dot_color = "#00ff88"
                        elif "breakthrough" in event_text.lower():
                            dot_color = "#ffd700"
                        elif "whisper" in event_text.lower() or "red pill" in event_text.lower():
                            dot_color = "#aa66ff"
                        else:
                            dot_color = "#5a8a5a"
                        timeline_html += (
                            f'<div style="display:flex;align-items:flex-start;gap:8px;margin:4px 0;font-size:0.75em;">'
                            f'<div style="width:8px;height:8px;border-radius:50%;background:{dot_color};'
                            f'margin-top:4px;flex-shrink:0;margin-left:-17px;"></div>'
                            f'<span style="color:#3a5a3a;min-width:40px;">t={tick_val}</span>'
                            f'<span style="color:{dot_color};">{event_text}</span>'
                            f'</div>'
                        )
                    timeline_html += '</div>'
                    st.markdown(timeline_html, unsafe_allow_html=True)

            # ── Inner monologue ──
            if agent.inner_monologue:
                with st.expander(f"\U0001f4ad Inner Thoughts ({len(agent.inner_monologue)} entries)", expanded=True):
                    for thought in reversed(agent.inner_monologue[-10:]):
                        st.markdown(f"---\n**t={thought['tick']}** | Priority: *{thought.get('priority', '?')}*")
                        st.markdown(f"> {thought.get('thought', '...')}")
            else:
                st.caption("\U0001f4ad No inner monologue yet — run more ticks to generate thoughts")

            st.divider()

        # Manual protagonist override
        st.markdown("#### Override Protagonists")
        all_adult_ids = [a.id for a in alive if a.phase == "adult"]
        if all_adult_ids:
            manual_picks = st.multiselect(
                "Select protagonists manually (up to 3)",
                all_adult_ids,
                default=[a.id for a in prot_agents if a.id in all_adult_ids],
                max_selections=3,
                format_func=lambda x: f"#{x}",
            )
            if st.button("Apply Selection"):
                engine.protagonist_ids = manual_picks
                for a in engine.agents:
                    a.is_protagonist = a.id in manual_picks
                st.toast(f"Protagonists set: {manual_picks}")
                st.rerun()
    else:
        st.info("No protagonists selected yet. Run more ticks to auto-select, or pick manually below.")
        all_adult_ids = [a.id for a in alive if a.phase == "adult"]
        if all_adult_ids:
            manual_picks = st.multiselect("Select protagonists", all_adult_ids,
                                           max_selections=3, format_func=lambda x: f"#{x}")
            if manual_picks and st.button("Set Protagonists"):
                engine.protagonist_ids = manual_picks
                for a in engine.agents:
                    a.is_protagonist = a.id in manual_picks
                    if a.is_protagonist and not a.protagonist_name:
                        a.protagonist_name = f"Agent-{a.id}"
                st.toast(f"Protagonists: {manual_picks}")
                st.rerun()
